### ISSUE TITLE
Две папки common

### ISSUE THREAD

**Issue by yshinkarev** [alfa-laboratory/alfa-ui-primitives#451]
В ходе #449 ПР был добавлен файл не в папку "common", а в "common " (в конце пробел).
Теперь нельзя склонировать репозитарий или распаковать исходники из zip-архива в ОС Windows.

**Comment by SiebenSieben** [comment]
@reme3d2y

**Comment by reme3d2y** [comment]
В фигме фрейм был с пробелом

- Переименовал его обратно
- Перенес иконку
- Добавил в плагин обрезку названий
